# Disabling sudo moves build to the Container Based Infrastructure on Travis CI.
sudo: false

language: java
jdk:
  - openjdk10

matrix:
  include:
  - jdk: openjdk10
    before_script:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

branches:
  only:
    - 1.x
    - 2.x
    - /^\d+\.\d+\.\d+(-\S*)?$/

install: true

git:
  depth: 150

jobs:
  include:
    - stage: build
      script: ./gradlew --no-daemon --info --stacktrace clean build
    - stage: release
      script:
        - ./gradlew --no-daemon --info --stacktrace bintrayUpload
        - curl -X POST -d '' $NETLIFY_DEPLOY_URL

stages:
  - build
  - name: release
    if: tag IS present

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle

notifications:
  email:
    recipients:
      - artem.zinnatullin@gmail.com
      - raniejaderamiso@gmail.com
    on_success: never
    on_failure: always
