# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 2.x

stages:
  - stage: Test
    jobs:
      - job: linux
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Gradle@2
            inputs:
              tasks: 'spek-runner:junit5:check integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'