# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 2.x

stages:
  - stage: Test
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Gradle@2
            inputs:
              tasks: 'spek-runner:junit5:check integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: MacOS
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - task: Gradle@2
            inputs:
              tasks: 'integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: Windows
        pool:
          vmImage: 'win1803'
        steps:
          - task: PowerShell@2
            inputs:
              filePath: '.\ci\install-jdk10.ps1'
          - pwsh: echo $env:JAVA_HOME
          - task: Gradle@2
            inputs:
              tasks: 'integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'
