name: Check PR - spek2
on:
  pull_request:
    paths:
      - 'spek-dsl/**'
      - 'spek-runtime/**'
      - 'spek-runner-junit5/**'
      - 'integration-test/**'
      - 'build.gradle.kts'
      - 'buildSrc/build.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/check-pr-core.yaml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            arguments: spek-runner-junit5:check integration-test:check -PexcludeIdePlugins
          - os: macos-latest
            arguments: integration-test:check -PexcludeIdePlugins
          - os: windows-latest
              arguments: integration-test:check -PexcludeIdePlugins
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: integration-test:check -PexcludeIdePlugins
